### ISSUE TITLE
Post merge container build is broken for ipxe

### ISSUE THREAD

**Issue by NymanRobin** [metal3-io/utility-images#10]
The IPXE container builds is not passing this needs to be fixed before any notification system is added to the builds.
The current error looks like the paths are relative to repository in container build but jenkins uses absolute path when running build this causes error. Fix might be to make all paths absolute
```
#4 CANCELED
------
 > [3/3] COPY buildipxe embed.ipxe.j2 /bin/:
------
Dockerfile:5
--------------------
   3 |     RUN dnf install -y gcc git-core make perl xz-devel python3-setuptools python3-jinja2
   4 |     
   5 | >>> COPY buildipxe embed.ipxe.j2 /bin/
   6 |     
   7 |     CMD /bin/buildipxe.sh
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref b2e5b9f7-0fd7-4608-8569-947c5fc96142::3hjpyyfbhby6np7ztniq5vp5f: "/buildipxe": not found
make: *** [Makefile:27: build-container-image] Error 1`

```

**Comment by NymanRobin** [comment]
The description of the issue is not correct got reminded that the build context of docker is relative to the dockerfile. The error seems to be that .sh ending is missing for the buildipxe file

**Comment by Rozzii** [comment]
Thanks for the fix.
/close
